### ISSUE TITLE
About Usage

### ISSUE THREAD

**Issue by TianzeWang-ZS** [sinansonmez/PowerpointUsefulAddin#2]
Hi Sinasonmez,

Just curious how to use / install these functions to powerpoint? Thank u!

**Comment by sinansonmez** [comment]
Hello TianzeWang-ZS,

You can use the codes to create your own functions with macro in PowerPoint. I also need to create an add-in so you can install the add-in and start using functionalities. It is in my todo list 

Best

**Comment by miguelcravo** [comment]
Hello,

First of all thank you for the macros.
Is it possible to use the macros across all presentations or do I always need to have the file with the macros open?

Thank you

**Comment by sinansonmez** [comment]
@miguelcravo hey. You have two options
- Macros enabled ppt: if you are using purely macro codes in my repo, unfortunately you need to open ppt with macros enabled. 
- No need to enable macros: There is a way to create a ribbon add-in with the macro codes in my repo. If you create an add-in, you can run the codes by clicking a button in the add-in. [Here](https://youtu.be/bUi-0wpMUHU) you can find a really simple video tutorial about how you can create an add-in. 

If you can create one, you may consider to share it with community so we can upload it here and every can benefit from it. 

Thanks

**Comment by miguelcravo** [comment]
Thank you so much for your help!
